/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.MedicalInfo;

/**
 *
 * @author lenovo
 */
public class CreateJPanel6 extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel6
     */
    
    MedicalInfo medicalinfo;
    
    public CreateJPanel6(MedicalInfo medicalinfo) {
        initComponents();
        this.medicalinfo = medicalinfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblmedicalRecord = new javax.swing.JLabel();
        lblmedicalRecordNum = new javax.swing.JLabel();
        txtmedicalRecordNum = new javax.swing.JTextField();
        lbldoctorName = new javax.swing.JLabel();
        txtdoctorName = new javax.swing.JTextField();
        lblallergy1 = new javax.swing.JLabel();
        txtallergy1 = new javax.swing.JTextField();
        lblallergy2 = new javax.swing.JLabel();
        txtallery2 = new javax.swing.JTextField();
        lblallergy3 = new javax.swing.JLabel();
        txtallergy3 = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();

        jTextField4.setText("jTextField1");

        lblmedicalRecord.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblmedicalRecord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmedicalRecord.setText("Medical Record");

        lblmedicalRecordNum.setText("Medical Record Number:");

        lbldoctorName.setText("Name of Doctor:");

        lblallergy1.setText("Allergy 1:");

        lblallergy2.setText("Allergy 2:");

        lblallergy3.setText("Allergy 3:");

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblmedicalRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbldoctorName)
                    .addComponent(lblmedicalRecordNum)
                    .addComponent(lblallergy1)
                    .addComponent(lblallergy2)
                    .addComponent(lblallergy3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmedicalRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtallergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave)
                    .addComponent(txtallery2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtallergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblmedicalRecord)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmedicalRecordNum)
                    .addComponent(txtmedicalRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldoctorName)
                    .addComponent(txtdoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblallergy1)
                    .addComponent(txtallergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtallery2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblallergy2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtallergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblallergy3))
                .addGap(18, 18, 18)
                .addComponent(btnsave)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        
        medicalinfo.setMedicalRecordNum(txtmedicalRecordNum.getText());
        medicalinfo.setDoctorName(txtdoctorName.getText());
        medicalinfo.setAllergy1(txtallergy1.getText());
        medicalinfo.setAllergy2(txtallery2.getText());
        medicalinfo.setAllergy3(txtallergy3.getText());
        
        JOptionPane.showMessageDialog(this, "Medical Information saved successfully");
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblallergy1;
    private javax.swing.JLabel lblallergy2;
    private javax.swing.JLabel lblallergy3;
    private javax.swing.JLabel lbldoctorName;
    private javax.swing.JLabel lblmedicalRecord;
    private javax.swing.JLabel lblmedicalRecordNum;
    private javax.swing.JTextField txtallergy1;
    private javax.swing.JTextField txtallergy3;
    private javax.swing.JTextField txtallery2;
    private javax.swing.JTextField txtdoctorName;
    private javax.swing.JTextField txtmedicalRecordNum;
    // End of variables declaration//GEN-END:variables
}
