/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.SavingsAccountInfo;

/**
 *
 * @author lenovo
 */
public class CreateJPanel3 extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel3
     */
    SavingsAccountInfo savingsaccountinfo;
    
    public CreateJPanel3(SavingsAccountInfo savingsaccountinfo) {
        initComponents();
        this.savingsaccountinfo = savingsaccountinfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtbankAccountNum = new javax.swing.JTextField();
        txtaccountBalance = new javax.swing.JTextField();
        txtaccountType = new javax.swing.JTextField();
        lblsavingsInfo = new javax.swing.JLabel();
        lblbankName = new javax.swing.JLabel();
        lblbankRoutingInfo = new javax.swing.JLabel();
        lblbankAccountNum = new javax.swing.JLabel();
        lblaccountBalance = new javax.swing.JLabel();
        lblaccountType = new javax.swing.JLabel();
        txtbankName = new javax.swing.JTextField();
        txtbankRoutingInfo = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();

        txtaccountType.setEditable(false);
        txtaccountType.setForeground(new java.awt.Color(102, 102, 102));
        txtaccountType.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtaccountType.setText("SAVINGS");

        lblsavingsInfo.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblsavingsInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsavingsInfo.setText("Savings Account Information");

        lblbankName.setText("Bank Name:");

        lblbankRoutingInfo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblbankRoutingInfo.setText("Bank Routing Information:");

        lblbankAccountNum.setText("Bank Account Number:");

        lblaccountBalance.setText("Account Balance:");

        lblaccountType.setText("Account Type:");

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblaccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtaccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblaccountBalance)
                                .addComponent(lblbankAccountNum))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtbankAccountNum, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                .addComponent(txtaccountBalance)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblbankName)
                                .addComponent(lblbankRoutingInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtbankName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtbankRoutingInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(85, Short.MAX_VALUE))
            .addComponent(lblsavingsInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtaccountBalance, txtbankAccountNum, txtbankName, txtbankRoutingInfo});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblsavingsInfo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbankName)
                    .addComponent(txtbankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbankRoutingInfo)
                    .addComponent(txtbankRoutingInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblbankAccountNum)
                    .addComponent(txtbankAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblaccountBalance)
                    .addComponent(txtaccountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtaccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsave))
                    .addComponent(lblaccountType))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtaccountBalance, txtbankAccountNum, txtbankName, txtbankRoutingInfo});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        
        savingsaccountinfo.setBankName(txtbankName.getText());
        savingsaccountinfo.setBankRoutingInfo(txtbankRoutingInfo.getText());
        savingsaccountinfo.setBankAccountNum(txtbankAccountNum.getText());
        savingsaccountinfo.setAccountBalance(txtaccountBalance.getText());
        
        JOptionPane.showMessageDialog(this, "Savings Account Information saved successfully");
        
        
    }//GEN-LAST:event_btnsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblaccountBalance;
    private javax.swing.JLabel lblaccountType;
    private javax.swing.JLabel lblbankAccountNum;
    private javax.swing.JLabel lblbankName;
    private javax.swing.JLabel lblbankRoutingInfo;
    private javax.swing.JLabel lblsavingsInfo;
    private javax.swing.JTextField txtaccountBalance;
    private javax.swing.JTextField txtaccountType;
    private javax.swing.JTextField txtbankAccountNum;
    private javax.swing.JTextField txtbankName;
    private javax.swing.JTextField txtbankRoutingInfo;
    // End of variables declaration//GEN-END:variables
}
