/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Component;
import model.AddressInfo;
import model.CheckingAccountInfo;
import model.LicenseInfo;
import model.MedicalInfo;
import model.Person;
import model.Report;
import model.SavingsAccountInfo;

/**
 *
 * @author lenovo
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     * 
     */
    
    Person person;
    AddressInfo addressinfo;
    SavingsAccountInfo savingsaccountinfo;
    CheckingAccountInfo checkingaccountinfo;
    LicenseInfo licenseinfo;
    MedicalInfo medicalinfo;
    Report report;
    
    public Component createPanel;
    public Component viewPanel;
    public Component reportpanel;
    
    public MainJFrame() {
        initComponents();
        
        person = new Person();
        addressinfo = new AddressInfo();
        savingsaccountinfo = new SavingsAccountInfo();
        checkingaccountinfo = new CheckingAccountInfo();
        licenseinfo = new LicenseInfo();
        medicalinfo = new MedicalInfo();
        report = new Report();
        
        this.setSize(550,550);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        workArea = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        btnCreate1 = new javax.swing.JButton();
        btnView1 = new javax.swing.JButton();
        lblPersonalInfo = new javax.swing.JLabel();
        btnCreate2 = new javax.swing.JButton();
        lblAddressInfo = new javax.swing.JLabel();
        btnView2 = new javax.swing.JButton();
        lblsavingsInfo = new javax.swing.JLabel();
        btnCreate3 = new javax.swing.JButton();
        btnView3 = new javax.swing.JButton();
        lblcheckingAccountInfo = new javax.swing.JLabel();
        btnCreate4 = new javax.swing.JButton();
        btnView4 = new javax.swing.JButton();
        lbllicenseInfo = new javax.swing.JLabel();
        btnCreate5 = new javax.swing.JButton();
        btnView5 = new javax.swing.JButton();
        btnreport = new javax.swing.JButton();
        lblmedicalInfo = new javax.swing.JLabel();
        btnCreate6 = new javax.swing.JButton();
        btnView6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        btnCreate1.setText("C");
        btnCreate1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51)));
        btnCreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate1ActionPerformed(evt);
            }
        });

        btnView1.setText("V");
        btnView1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        btnView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView1ActionPerformed(evt);
            }
        });

        lblPersonalInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPersonalInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonalInfo.setText("Personal");

        btnCreate2.setText("C");
        btnCreate2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102)));
        btnCreate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate2ActionPerformed(evt);
            }
        });

        lblAddressInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAddressInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddressInfo.setText("Address");

        btnView2.setText("V");
        btnView2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        btnView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView2ActionPerformed(evt);
            }
        });

        lblsavingsInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblsavingsInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsavingsInfo.setText("Savings Acc Info");

        btnCreate3.setText("C");
        btnCreate3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51)));
        btnCreate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate3ActionPerformed(evt);
            }
        });

        btnView3.setText("V");
        btnView3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        btnView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView3ActionPerformed(evt);
            }
        });

        lblcheckingAccountInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblcheckingAccountInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcheckingAccountInfo.setText("Checking Acc Info");

        btnCreate4.setText("C");
        btnCreate4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51)));
        btnCreate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate4ActionPerformed(evt);
            }
        });

        btnView4.setText("V");
        btnView4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        btnView4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView4ActionPerformed(evt);
            }
        });

        lbllicenseInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbllicenseInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllicenseInfo.setText("License Info");

        btnCreate5.setText("C");
        btnCreate5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51)));
        btnCreate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate5ActionPerformed(evt);
            }
        });

        btnView5.setText("V");
        btnView5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        btnView5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView5ActionPerformed(evt);
            }
        });

        btnreport.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        btnreport.setText("Get Report");
        btnreport.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        btnreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportActionPerformed(evt);
            }
        });

        lblmedicalInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblmedicalInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmedicalInfo.setText("Medical Info");

        btnCreate6.setText("C");
        btnCreate6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51)));
        btnCreate6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate6ActionPerformed(evt);
            }
        });

        btnView6.setText("V");
        btnView6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        btnView6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAddressInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnCreate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnView2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addComponent(lblsavingsInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblcheckingAccountInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbllicenseInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                        .addComponent(btnCreate4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnView4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                        .addComponent(btnCreate5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnView5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))))
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmedicalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnreport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addComponent(btnCreate6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnView6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(8, 8, 8)))
                .addContainerGap())
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(btnCreate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(btnCreate3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnView3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblPersonalInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnView2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddressInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnView1)
                    .addComponent(btnCreate2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsavingsInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView3)
                    .addComponent(btnCreate3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblcheckingAccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate4)
                    .addComponent(btnView4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbllicenseInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreate5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnView5))
                .addGap(7, 7, 7)
                .addComponent(lblmedicalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate6)
                    .addComponent(btnView6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnreport, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        splitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate1ActionPerformed
        // TODO add your handling code here:
        
         CreateJPanel1 createPanel = new CreateJPanel1(person);
        splitPane.setRightComponent(createPanel);
        
        
    }//GEN-LAST:event_btnCreate1ActionPerformed

    private void btnView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView2ActionPerformed
        // TODO add your handling code here:
        
        ViewJPanel1 viewPanel = new ViewJPanel1(person);
        splitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_btnView2ActionPerformed

    private void btnCreate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate2ActionPerformed
        // TODO add your handling code here:
        CreateJPanel2 createPanel = new CreateJPanel2(addressinfo);
        splitPane.setRightComponent(createPanel); 
    }//GEN-LAST:event_btnCreate2ActionPerformed

    private void btnView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView1ActionPerformed
        // TODO add your handling code here:
        
        ViewJPanel2 viewPanel = new ViewJPanel2(addressinfo);
        splitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_btnView1ActionPerformed

    private void btnCreate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate3ActionPerformed
        // TODO add your handling code here:
        CreateJPanel3 createPanel = new CreateJPanel3(savingsaccountinfo);
        splitPane.setRightComponent(createPanel); 
        
    }//GEN-LAST:event_btnCreate3ActionPerformed

    private void btnView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView3ActionPerformed
        // TODO add your handling code here:
        ViewJPanel3 viewPanel = new ViewJPanel3(savingsaccountinfo);
        splitPane.setRightComponent(viewPanel);
        
    }//GEN-LAST:event_btnView3ActionPerformed

    private void btnCreate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate4ActionPerformed
        // TODO add your handling code here:
        
        CreateJPanel4 createPanel = new CreateJPanel4(checkingaccountinfo);
        splitPane.setRightComponent(createPanel); 
        
        
    }//GEN-LAST:event_btnCreate4ActionPerformed

    private void btnView4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView4ActionPerformed
        // TODO add your handling code here:
        
        ViewJPanel4 viewPanel = new ViewJPanel4(checkingaccountinfo);
        splitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_btnView4ActionPerformed

    private void btnCreate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate5ActionPerformed
        // TODO add your handling code here:
        
        CreateJPanel5 createPanel = new CreateJPanel5(licenseinfo);
        splitPane.setRightComponent(createPanel);
        
    }//GEN-LAST:event_btnCreate5ActionPerformed

    private void btnView5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView5ActionPerformed
        // TODO add your handling code here:
        
        ViewJPanel5 viewPanel = new ViewJPanel5(licenseinfo);
        splitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_btnView5ActionPerformed

    private void btnCreate6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate6ActionPerformed
        // TODO add your handling code here:
        
        CreateJPanel6 createPanel = new CreateJPanel6(medicalinfo);
        splitPane.setRightComponent(createPanel); 
        
    }//GEN-LAST:event_btnCreate6ActionPerformed

    private void btnView6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView6ActionPerformed
        // TODO add your handling code here:
        
         ViewJPanel6 viewPanel = new ViewJPanel6(medicalinfo);
        splitPane.setRightComponent(viewPanel);
        
        
    }//GEN-LAST:event_btnView6ActionPerformed

    private void btnreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportActionPerformed
        // TODO add your handling code here:
        
        report.setreportperson(person);
        report.setReportaddressinfo(addressinfo);
        report.setReportsavingsaccountinfo(savingsaccountinfo);
        report.setReportcheckingaccountinfo(checkingaccountinfo);
        report.setReportlicenseinfo(licenseinfo);
        report.setReportmedicalinfo(medicalinfo);
        
        
        ReportPanel reportpanel = new ReportPanel(report);
        splitPane.setRightComponent(reportpanel);
        
        reportpanel.displayreport();
        
        
        
    }//GEN-LAST:event_btnreportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate1;
    private javax.swing.JButton btnCreate2;
    private javax.swing.JButton btnCreate3;
    private javax.swing.JButton btnCreate4;
    private javax.swing.JButton btnCreate5;
    private javax.swing.JButton btnCreate6;
    private javax.swing.JButton btnView1;
    private javax.swing.JButton btnView2;
    private javax.swing.JButton btnView3;
    private javax.swing.JButton btnView4;
    private javax.swing.JButton btnView5;
    private javax.swing.JButton btnView6;
    private javax.swing.JButton btnreport;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel lblAddressInfo;
    private javax.swing.JLabel lblPersonalInfo;
    private javax.swing.JLabel lblcheckingAccountInfo;
    private javax.swing.JLabel lbllicenseInfo;
    private javax.swing.JLabel lblmedicalInfo;
    private javax.swing.JLabel lblsavingsInfo;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables

    //private javax.swing.JTextField txtfirstName;
    
    
}
