/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Person;
import model.Report;

/**
 *
 * @author lenovo
 */
public class ReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportPanel
     */
    Report report;
    //Person person;
    
    public ReportPanel(Report report) {
        initComponents();
        this.report = report;
        displayreport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtaccountBalance2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lbllicenseNum = new javax.swing.JLabel();
        lblbankName1 = new javax.swing.JLabel();
        lbldateOfIssue = new javax.swing.JLabel();
        lblbankRoutingInfo1 = new javax.swing.JLabel();
        lbldateOfExpiry = new javax.swing.JLabel();
        lblbankAccountNum1 = new javax.swing.JLabel();
        lblaccountBalance1 = new javax.swing.JLabel();
        lblbloodType = new javax.swing.JLabel();
        txtlicenseNumber = new javax.swing.JTextField();
        txtbankName1 = new javax.swing.JTextField();
        txtbankRoutingInfo1 = new javax.swing.JTextField();
        txtbankAccountNum1 = new javax.swing.JTextField();
        txtaccountBalance1 = new javax.swing.JTextField();
        lblreport = new javax.swing.JLabel();
        txtdateOfIssue = new javax.swing.JTextField();
        txtdateOfExpiry = new javax.swing.JTextField();
        txtbloodType = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        lblmedicalRecordNum = new javax.swing.JLabel();
        lbldoctorName = new javax.swing.JLabel();
        lblallergy1 = new javax.swing.JLabel();
        txtmedicalRecordNum = new javax.swing.JTextField();
        txtdoctorName = new javax.swing.JTextField();
        txtallergy1 = new javax.swing.JTextField();
        lblbankName2 = new javax.swing.JLabel();
        lblbankRoutingInfo2 = new javax.swing.JLabel();
        lblbankAccountNum2 = new javax.swing.JLabel();
        lblaccountBalance2 = new javax.swing.JLabel();
        txtbankName2 = new javax.swing.JTextField();
        txtbankRoutingInfo2 = new javax.swing.JTextField();
        txtbankAccountNum2 = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        lblweight = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        lbllastName = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        txtstreetAddress = new javax.swing.JTextField();
        ImageUpload = new javax.swing.JButton();
        txtzipCode = new javax.swing.JTextField();
        txtheight = new javax.swing.JTextField();
        lblfirstName = new javax.swing.JLabel();
        txtdateOfBirth = new javax.swing.JTextField();
        lblphoneNum = new javax.swing.JLabel();
        lblstreetAddress = new javax.swing.JLabel();
        lbldateOfBirth = new javax.swing.JLabel();
        txtweight = new javax.swing.JTextField();
        lblcity = new javax.swing.JLabel();
        txtssn = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        txtlastName = new javax.swing.JTextField();
        txtstate = new javax.swing.JTextField();
        lblheight = new javax.swing.JLabel();
        txtfirstName = new javax.swing.JTextField();
        lblstate = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        txtphoneNum = new javax.swing.JTextField();
        lblzipCode = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtaccountBalance2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("SAVINGS & CHECKING ACCOUNT DETAILS");

        lbllicenseNum.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbllicenseNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbllicenseNum.setText("Lic Num:");

        lblbankName1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblbankName1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblbankName1.setText("Bank Name: (S)");

        lbldateOfIssue.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbldateOfIssue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbldateOfIssue.setText("DOI:");

        lblbankRoutingInfo1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblbankRoutingInfo1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblbankRoutingInfo1.setText("Routing Info:");

        lbldateOfExpiry.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbldateOfExpiry.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbldateOfExpiry.setText("DOE:");

        lblbankAccountNum1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblbankAccountNum1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblbankAccountNum1.setText("Acc Num:");

        lblaccountBalance1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblaccountBalance1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblaccountBalance1.setText("Acc Bal:");

        lblbloodType.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblbloodType.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblbloodType.setText("Blood Type:");

        txtlicenseNumber.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtbankName1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtbankRoutingInfo1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtbankAccountNum1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtaccountBalance1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblreport.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblreport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblreport.setText("Report");

        txtdateOfIssue.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtdateOfExpiry.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtbloodType.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("LICENSE AND MEDICAL RECORDS");

        lblmedicalRecordNum.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblmedicalRecordNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblmedicalRecordNum.setText("Rec Num:");

        lbldoctorName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbldoctorName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbldoctorName.setText("Doctor:");

        lblallergy1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblallergy1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblallergy1.setText("Allergy1:");

        txtmedicalRecordNum.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtdoctorName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtallergy1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblbankName2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblbankName2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblbankName2.setText("BankName: (C)");

        lblbankRoutingInfo2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblbankRoutingInfo2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblbankRoutingInfo2.setText("Routing Info:");

        lblbankAccountNum2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblbankAccountNum2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblbankAccountNum2.setText("Acc Num:");

        lblaccountBalance2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblaccountBalance2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblaccountBalance2.setText("Acc Bal:");

        txtbankName2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtbankRoutingInfo2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtbankAccountNum2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jInternalFrame1.setVisible(true);

        lblweight.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblweight.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblweight.setText("Weight:");

        txtcity.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lbllastName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbllastName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbllastName.setText("Last name:");

        lblage.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblage.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblage.setText("Age:");

        txtstreetAddress.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtstreetAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ImageUpload.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ImageUpload.setText("Browse");
        ImageUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageUploadActionPerformed(evt);
            }
        });

        txtzipCode.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtheight.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblfirstName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblfirstName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblfirstName.setText("First name:");

        txtdateOfBirth.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblphoneNum.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblphoneNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblphoneNum.setText("Phone Num:");

        lblstreetAddress.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblstreetAddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblstreetAddress.setText("Address:");

        lbldateOfBirth.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbldateOfBirth.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbldateOfBirth.setText("DOB:");

        txtweight.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblcity.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblcity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblcity.setText("City:");

        txtssn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        image.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setText("Upload Image Here");
        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        image.setMaximumSize(new java.awt.Dimension(30, 10));
        image.setMinimumSize(new java.awt.Dimension(30, 10));
        image.setPreferredSize(new java.awt.Dimension(30, 10));

        txtlastName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtstate.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblheight.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblheight.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblheight.setText("Height:");

        txtfirstName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblstate.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblstate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblstate.setText("State:");

        lblssn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblssn.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblssn.setText("SSN:");

        txtage.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtphoneNum.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblzipCode.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblzipCode.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblzipCode.setText("Zip Code:");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(lblage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(lbldateOfBirth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblphoneNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbllastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblfirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblheight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblweight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblssn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtlastName)
                    .addComponent(txtphoneNum)
                    .addComponent(txtdateOfBirth)
                    .addComponent(txtage)
                    .addComponent(txtheight)
                    .addComponent(txtweight)
                    .addComponent(txtssn)
                    .addComponent(txtfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblcity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblstreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblstate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblzipCode, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstate, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtzipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ImageUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jInternalFrame1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtcity, txtstate, txtstreetAddress, txtzipCode});

        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(ImageUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtstreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblstreetAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblstate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtzipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblzipCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblfirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbllastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtlastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtphoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblphoneNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbldateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                            .addComponent(txtdateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtheight, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblheight, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblweight, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblssn))))
                .addContainerGap())
        );

        jInternalFrame1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtcity, txtstate, txtstreetAddress, txtzipCode});

        jInternalFrame1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtage, txtdateOfBirth, txtfirstName, txtheight, txtlastName, txtphoneNum, txtssn, txtweight});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblreport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lbldateOfExpiry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbllicenseNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(lbldateOfIssue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblbloodType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtlicenseNumber)
                            .addComponent(txtdateOfIssue)
                            .addComponent(txtdateOfExpiry)
                            .addComponent(txtbloodType))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblmedicalRecordNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lbldoctorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblallergy1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtdoctorName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmedicalRecordNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtallergy1))
                        .addGap(95, 95, 95))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblbankName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(lblbankAccountNum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblbankRoutingInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblaccountBalance1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(3, 3, 3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtbankName1)
                                .addGap(2, 2, 2))
                            .addComponent(txtbankRoutingInfo1)
                            .addComponent(txtbankAccountNum1)
                            .addComponent(txtaccountBalance1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(lblbankRoutingInfo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(lblbankAccountNum2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(lblaccountBalance2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblbankName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbankName2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtaccountBalance2)
                            .addComponent(txtbankAccountNum2)
                            .addComponent(txtbankRoutingInfo2))
                        .addGap(91, 91, 91))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblreport, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInternalFrame1)
                .addGap(8, 8, 8)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbankAccountNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbankAccountNum2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtaccountBalance2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblbankName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtbankName1))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblbankRoutingInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtbankRoutingInfo1))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblbankAccountNum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtbankAccountNum1))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblaccountBalance1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtaccountBalance1))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblbankName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtbankName2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblbankRoutingInfo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtbankRoutingInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(lblaccountBalance2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)))
                .addComponent(jLabel30)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblmedicalRecordNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(txtmedicalRecordNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdoctorName)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lbldoctorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtallergy1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblallergy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbllicenseNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(lbldateOfIssue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(13, 13, 13)
                                .addComponent(lbldateOfExpiry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(13, 13, 13)
                                .addComponent(lblbloodType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtlicenseNumber)
                                .addGap(12, 12, 12)
                                .addComponent(txtdateOfIssue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdateOfExpiry)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbloodType)))
                        .addGap(12, 12, 12))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ImageUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageUploadActionPerformed
        // TODO add your handling code here:
        
     JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES","png","jpg","jpeg");
        chooser.addChoosableFileFilter(fnef);
        int showOpenDialogue = chooser.showOpenDialog(null);
        
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
           File selectImageFile = chooser.getSelectedFile();
           report.setSetFilePath(selectImageFile.getAbsolutePath());
        
           ImageIcon ii = new ImageIcon(report.getSetFilePath());
           image.setIcon(ii);
        
        }
        
        
        
        
    }//GEN-LAST:event_ImageUploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ImageUpload;
    private javax.swing.JLabel image;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblaccountBalance1;
    private javax.swing.JLabel lblaccountBalance2;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblallergy1;
    private javax.swing.JLabel lblbankAccountNum1;
    private javax.swing.JLabel lblbankAccountNum2;
    private javax.swing.JLabel lblbankName1;
    private javax.swing.JLabel lblbankName2;
    private javax.swing.JLabel lblbankRoutingInfo1;
    private javax.swing.JLabel lblbankRoutingInfo2;
    private javax.swing.JLabel lblbloodType;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lbldateOfBirth;
    private javax.swing.JLabel lbldateOfExpiry;
    private javax.swing.JLabel lbldateOfIssue;
    private javax.swing.JLabel lbldoctorName;
    private javax.swing.JLabel lblfirstName;
    private javax.swing.JLabel lblheight;
    private javax.swing.JLabel lbllastName;
    private javax.swing.JLabel lbllicenseNum;
    private javax.swing.JLabel lblmedicalRecordNum;
    private javax.swing.JLabel lblphoneNum;
    private javax.swing.JLabel lblreport;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lblstreetAddress;
    private javax.swing.JLabel lblweight;
    private javax.swing.JLabel lblzipCode;
    private javax.swing.JTextField txtaccountBalance1;
    private javax.swing.JTextField txtaccountBalance2;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtallergy1;
    private javax.swing.JTextField txtbankAccountNum1;
    private javax.swing.JTextField txtbankAccountNum2;
    private javax.swing.JTextField txtbankName1;
    private javax.swing.JTextField txtbankName2;
    private javax.swing.JTextField txtbankRoutingInfo1;
    private javax.swing.JTextField txtbankRoutingInfo2;
    private javax.swing.JTextField txtbloodType;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtdateOfBirth;
    private javax.swing.JTextField txtdateOfExpiry;
    private javax.swing.JTextField txtdateOfIssue;
    private javax.swing.JTextField txtdoctorName;
    private javax.swing.JTextField txtfirstName;
    private javax.swing.JTextField txtheight;
    private javax.swing.JTextField txtlastName;
    private javax.swing.JTextField txtlicenseNumber;
    private javax.swing.JTextField txtmedicalRecordNum;
    private javax.swing.JTextField txtphoneNum;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtstreetAddress;
    private javax.swing.JTextField txtweight;
    private javax.swing.JTextField txtzipCode;
    // End of variables declaration//GEN-END:variables

public void displayreport() {
        
        txtfirstName.setText(report.getreportperson().getFirstName());
        txtlastName.setText(report.getreportperson().getLastName());
        txtphoneNum.setText(report.getreportperson().getPhoneNum());
        txtdateOfBirth.setText(report.getreportperson().getBirthDate());
        txtage.setText(report.getreportperson().getAge());
        txtheight.setText(report.getreportperson().getHeight());
        txtweight.setText(report.getreportperson().getWeight());
        txtssn.setText(report.getreportperson().getSsn());
    
        txtstreetAddress.setText(report.getReportaddressinfo().getStreetAddress());
        txtcity.setText(report.getReportaddressinfo().getCity());
        txtstate.setText(report.getReportaddressinfo().getState());
        txtzipCode.setText(report.getReportaddressinfo().getZipcode());
        
        txtbankName1.setText(report.getReportsavingsaccountinfo().getBankName());
        txtbankRoutingInfo1.setText(report.getReportsavingsaccountinfo().getBankRoutingInfo());
        txtbankAccountNum1.setText(report.getReportsavingsaccountinfo().getBankAccountNum());
        txtaccountBalance1.setText(report.getReportsavingsaccountinfo().getAccountBalance());              
    
        
        txtbankName2.setText(report.getReportcheckingaccountinfo().getBankName());
        txtbankRoutingInfo2.setText(report.getReportcheckingaccountinfo().getBankRoutingInfo());
        txtbankAccountNum2.setText(report.getReportcheckingaccountinfo().getBankAccountNum());
        txtaccountBalance2.setText(report.getReportcheckingaccountinfo().getAccountBalance());
        
        txtlicenseNumber.setText(report.getReportlicenseinfo().getLicenseNum());
        txtdateOfIssue.setText(report.getReportlicenseinfo().getDateOfIssue());
        txtdateOfExpiry.setText(report.getReportlicenseinfo().getDateOfExpiry());
        txtbloodType.setText(report.getReportlicenseinfo().getBloodType());
        
        txtmedicalRecordNum.setText(report.getReportmedicalinfo().getMedicalRecordNum());
        txtdoctorName.setText(report.getReportmedicalinfo().getDoctorName());
        txtallergy1.setText(report.getReportmedicalinfo().getAllergy1());
        
        
       // report.setFirstName((person.getFirstName()));
        //txtfirstName.setText(report.getFirstName());
       // txtfirstName.setText(person.getFirstName());
        
        
       /* report.txtfirstName.setText(person.getFirstName());
        report.txtlastName.setText(person.getLastName());
        report.txtphoneNum.setText(person.getPhoneNum());
        report.txtbirthDate.setText(person.getBirthDate());
        report.txtage.setText(person.getAge());
        report.txtheight.setText(person.getHeight());
        report.txtweight.setText(person.getWeight());
        report.txtssn.setText(person.getSsn());*/
        
    }






}
