/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.LicenseInfo;

/**
 *
 * @author lenovo
 */
public class ViewJPanel5 extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel5
     */
    
    LicenseInfo licenseinfo;
    
    public ViewJPanel5(LicenseInfo licenseinfo) {
        initComponents();
        this.licenseinfo = licenseinfo;
        
        displaylicenseInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtbloodType = new javax.swing.JTextField();
        txtdateOfExpiry = new javax.swing.JTextField();
        lbldateOfExpiry = new javax.swing.JLabel();
        lblbloodType = new javax.swing.JLabel();
        txtdateOfIssue = new javax.swing.JTextField();
        lbldateOfIssue = new javax.swing.JLabel();
        lbllicenseNum = new javax.swing.JLabel();
        txtlicenseNum = new javax.swing.JTextField();
        lbllicenseInfo = new javax.swing.JLabel();

        txtbloodType.setEditable(false);

        txtdateOfExpiry.setEditable(false);

        lbldateOfExpiry.setText("Date of Expiry:");

        lblbloodType.setText("Blood Type:");

        txtdateOfIssue.setEditable(false);

        lbldateOfIssue.setText("Date of Issue:");

        lbllicenseNum.setText("License Number:");

        txtlicenseNum.setEditable(false);

        lbllicenseInfo.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lbllicenseInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllicenseInfo.setText("License Information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbllicenseInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbldateOfIssue)
                        .addGap(18, 18, 18)
                        .addComponent(txtdateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbllicenseNum)
                        .addGap(18, 18, 18)
                        .addComponent(txtlicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblbloodType)
                        .addGap(18, 18, 18)
                        .addComponent(txtbloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbldateOfExpiry)
                        .addGap(18, 18, 18)
                        .addComponent(txtdateOfExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtbloodType, txtdateOfExpiry, txtdateOfIssue, txtlicenseNum});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbllicenseInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllicenseNum)
                    .addComponent(txtlicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldateOfIssue)
                    .addComponent(txtdateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldateOfExpiry)
                    .addComponent(txtdateOfExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbloodType)
                    .addComponent(txtbloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblbloodType;
    private javax.swing.JLabel lbldateOfExpiry;
    private javax.swing.JLabel lbldateOfIssue;
    private javax.swing.JLabel lbllicenseInfo;
    private javax.swing.JLabel lbllicenseNum;
    private javax.swing.JTextField txtbloodType;
    private javax.swing.JTextField txtdateOfExpiry;
    private javax.swing.JTextField txtdateOfIssue;
    private javax.swing.JTextField txtlicenseNum;
    // End of variables declaration//GEN-END:variables

    private void displaylicenseInfo() {
        
         txtlicenseNum.setText(licenseinfo.getLicenseNum());
         txtdateOfIssue.setText(licenseinfo.getDateOfIssue());
         txtdateOfExpiry.setText(licenseinfo.getDateOfExpiry());
         txtbloodType.setText(licenseinfo.getBloodType());
        
        
         /*txtlicenseNum.setText(licenseinfo.getLicenseNum());
         txtdateOfIssue.setText(licenseinfo.getDateOfIssue());
         txtdateOfExpiry.setText(licenseinfo.getDateOfExpiry());
         txtbloodType.setText(licenseinfo.getBloodType());*/
    }
}
