/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.MedicalInfo;

/**
 *
 * @author lenovo
 */
public class ViewJPanel6 extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel6
     */
    MedicalInfo medicalinfo;
            
    public ViewJPanel6(MedicalInfo medicalinfo) {
        initComponents();
        this.medicalinfo = medicalinfo;
        displaymedicalInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblmedicalRecordNum = new javax.swing.JLabel();
        lbldoctorName = new javax.swing.JLabel();
        lblallergy1 = new javax.swing.JLabel();
        lblallergy2 = new javax.swing.JLabel();
        txtmedicalRecordNum = new javax.swing.JTextField();
        lblallergy3 = new javax.swing.JLabel();
        txtdoctorName = new javax.swing.JTextField();
        txtallergy1 = new javax.swing.JTextField();
        txtallergy2 = new javax.swing.JTextField();
        txtallergy3 = new javax.swing.JTextField();
        lblmedicalRecord = new javax.swing.JLabel();

        lblmedicalRecordNum.setText("Medical Record Number:");

        lbldoctorName.setText("Name of Doctor:");

        lblallergy1.setText("Allergy 1:");

        lblallergy2.setText("Allergy 2:");

        txtmedicalRecordNum.setEditable(false);

        lblallergy3.setText("Allergy 3:");

        txtdoctorName.setEditable(false);
        txtdoctorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdoctorNameActionPerformed(evt);
            }
        });

        txtallergy1.setEditable(false);

        txtallergy2.setEditable(false);

        txtallergy3.setEditable(false);

        lblmedicalRecord.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblmedicalRecord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmedicalRecord.setText("Medical Record");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmedicalRecord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblallergy3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtallergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblallergy1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtallergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblallergy2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtallergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblmedicalRecordNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtmedicalRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbldoctorName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtallergy1, txtallergy2, txtallergy3, txtdoctorName, txtmedicalRecordNum});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblmedicalRecord)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmedicalRecordNum)
                    .addComponent(txtmedicalRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldoctorName)
                    .addComponent(txtdoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtallergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblallergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtallergy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblallergy2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblallergy3)
                    .addComponent(txtallergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtdoctorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdoctorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdoctorNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblallergy1;
    private javax.swing.JLabel lblallergy2;
    private javax.swing.JLabel lblallergy3;
    private javax.swing.JLabel lbldoctorName;
    private javax.swing.JLabel lblmedicalRecord;
    private javax.swing.JLabel lblmedicalRecordNum;
    private javax.swing.JTextField txtallergy1;
    private javax.swing.JTextField txtallergy2;
    private javax.swing.JTextField txtallergy3;
    private javax.swing.JTextField txtdoctorName;
    private javax.swing.JTextField txtmedicalRecordNum;
    // End of variables declaration//GEN-END:variables

    private void displaymedicalInfo() {
        txtmedicalRecordNum.setText(medicalinfo.getMedicalRecordNum());
         txtdoctorName.setText(medicalinfo.getDoctorName());
         txtallergy1.setText(medicalinfo.getAllergy1());
         txtallergy2.setText(medicalinfo.getAllergy2());
         txtallergy3.setText(medicalinfo.getAllergy3());
    }
}
