/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.CheckingAccountInfo;

/**
 *
 * @author lenovo
 */
public class ViewJPanel4 extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel4
     */
    
    CheckingAccountInfo checkingaccountinfo;
    
    public ViewJPanel4(CheckingAccountInfo checkingaccountinfo) {
        initComponents();
        
        this.checkingaccountinfo = checkingaccountinfo;
        displayCheckingInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtbankName = new javax.swing.JTextField();
        txtbankRoutingInfo = new javax.swing.JTextField();
        txtbankAccountNum = new javax.swing.JTextField();
        lblaccountType1 = new javax.swing.JLabel();
        txtaccountBalance = new javax.swing.JTextField();
        txtaccountType1 = new javax.swing.JTextField();
        lblcheckingInfo = new javax.swing.JLabel();
        lblbankName = new javax.swing.JLabel();
        lblbankRoutingInfo = new javax.swing.JLabel();
        lblbankAccountNum = new javax.swing.JLabel();
        lblaccountBalance = new javax.swing.JLabel();

        txtbankName.setEditable(false);

        txtbankRoutingInfo.setEditable(false);

        txtbankAccountNum.setEditable(false);

        lblaccountType1.setText("Account Type:");

        txtaccountBalance.setEditable(false);

        txtaccountType1.setEditable(false);
        txtaccountType1.setForeground(new java.awt.Color(102, 102, 102));
        txtaccountType1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtaccountType1.setText("CHECKING");

        lblcheckingInfo.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblcheckingInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcheckingInfo.setText("Checking Account Information");

        lblbankName.setText("Bank Name:");

        lblbankRoutingInfo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblbankRoutingInfo.setText("Bank Routing Information:");

        lblbankAccountNum.setText("Bank Account Number:");

        lblaccountBalance.setText("Account Balance:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcheckingInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblaccountBalance)
                    .addComponent(lblbankAccountNum)
                    .addComponent(lblbankName)
                    .addComponent(lblbankRoutingInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtbankName, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addComponent(txtbankRoutingInfo)
                        .addComponent(txtbankAccountNum))
                    .addComponent(txtaccountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblaccountType1)
                .addGap(18, 18, 18)
                .addComponent(txtaccountType1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblcheckingInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbankName)
                    .addComponent(txtbankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbankRoutingInfo)
                    .addComponent(txtbankRoutingInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbankAccountNum)
                    .addComponent(txtbankAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblaccountBalance)
                    .addComponent(txtaccountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblaccountType1)
                    .addComponent(txtaccountType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblaccountBalance;
    private javax.swing.JLabel lblaccountType1;
    private javax.swing.JLabel lblbankAccountNum;
    private javax.swing.JLabel lblbankName;
    private javax.swing.JLabel lblbankRoutingInfo;
    private javax.swing.JLabel lblcheckingInfo;
    private javax.swing.JTextField txtaccountBalance;
    private javax.swing.JTextField txtaccountType1;
    private javax.swing.JTextField txtbankAccountNum;
    private javax.swing.JTextField txtbankName;
    private javax.swing.JTextField txtbankRoutingInfo;
    // End of variables declaration//GEN-END:variables

    private void displayCheckingInfo() {
         txtbankName.setText(checkingaccountinfo.getBankName());
         txtbankRoutingInfo.setText(checkingaccountinfo.getBankRoutingInfo());
         txtbankAccountNum.setText(checkingaccountinfo.getBankAccountNum());
         txtaccountBalance.setText(checkingaccountinfo.getAccountBalance());
    }
}
